version: "3.8"
services:
  vms-client:
    image: vmsacr.azurecr.io/web-vms:latest
    restart: always
    volumes:
      - nginx-config:/usr/share/nginx/html/config
    build: .
    container_name: web-vms
    ports:
      - "3000:80" # map 80 in container => 3000 in local
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - WEBSITE_TIME_ZONE=Asia/Ho_Chi_Minh
