version: "3.8"
services:
  vms-client:
    restart: always
    volumes:
      - ./.nginx/html/config:/usr/share/nginx/html/config
    build: .
    container_name: vms-client
    ports:
      - "3000:80" # map 80 in container => 3000 in local
    networks:
      - vms

networks:
  vms:
    name: vms-network
    driver: bridge
