version: "3.8"
services:
  vms-client:
    restart: always
#    volumes:
#      - ./nginx/config/runtime-config.js:/usr/share/nginx/html/runtime-config.js
#      - ./nginx/config/keycloak.json:/usr/share/nginx/html/keycloak.json
    build: .
    container_name: vms-client
    ports:
      - "3000:80" # map 80 in container => 3000 in local
    networks:
      - vms

networks:
  vms:
    name: vms-network
    driver: bridge
