export const PATH_ROLE_MAP = {
  'PATH_DASHBOARD': ['path:dashboard'],
  'PATH_CONFIGURATION': ['path:configuration'],
  'PATH_CUSTOMER': ['path:customer'],
  'PATH_DEPARTMENT': ['path:department'],
  'PATH_DEVICE': ['path:device'],
  'PATH_HISTORY': ['path:history'],
  'PATH_MEETING_CALENDAR': ['path:meeting_calendar'],
  'PATH_MEETING_STATISTIC': ['path:meeting_statistic'],
  'PATH_MEETING_ROOM': ['path:meeting_room'],
  'PATH_ORGANIZATION': ['path:organization'],
  'PATH_MY_ORGANIZATION': ['path:my_organization'],
  'PATH_MY_SITE': ['path:my_site'],
  'PATH_AUDIT_LOG': ['path:audit_log'],
  'PATH_PERMISSION': ['path:permission'],
  'PATH_PROFILE': ['path:profile'],
  'PATH_ROOM': ['path:room'],
  'PATH_SITE': ['path:site'],
  'PATH_TEMPLATE': ['path:template'],
  'PATH_TICKET_RESULT': ['path:ticket_result'],
  'PATH_CHECK_IN_MANAGER': ['path:check_in_manager'],
  'PATH_QR_CODE_MANAGER': ['path:qr_code_manager'],
  'PATH_USER': ['path:user'],
  'PATH_ROLE': ['path:role']
}

export const SCOPE_ROLE_MAP = {
  'SCOPE_ORGANIZATION': ['scope:organization'],
  'SCOPE_SITE': ['scope:site']
}

export const PERMISSION_ROLE_MAP = {
  'R_CARD_DELETE': ['r:card:delete'],
  'R_CUSTOMER_CREATE': ['r:customer:create'],
  'R_CUSTOMER_FIND': ['r:customer:find'],
  'R_DEPARTMENT_CREATE': ['r:department:create'],
  'R_DEPARTMENT_DELETE': ['r:department:delete'],
  'R_DEPARTMENT_FIND': ['r:department:find'],
  'R_DEPARTMENT_UPDATE': ['r:department:update'],
  'R_FILE_UPLOAD': ['r:file:upload'],
  'R_ORGANIZATION_CREATE': ['r:organization:create'],
  'R_ORGANIZATION_DELETE': ['r:organization:delete'],
  'R_ORGANIZATION_FIND': ['r:organization:find'],
  'R_ORGANIZATION_UPDATE': ['r:organization:update'],
  'R_PERMISSION_CREATE': ['r:permission:create'],
  'R_PERMISSION_DELETE': ['r:permission:delete'],
  'R_PERMISSION_FIND': ['r:permission:find'],
  'R_PERMISSION_UPDATE': ['r:permission:update'],
  'R_REASON_CREATE': ['r:reason:create'],
  'R_REASON_DELETE': ['r:reason:delete'],
  'R_REASON_UPDATE': ['r:reason:update'],
  'R_ROLE_CREATE': ['r:role:create'],
  'R_ROLE_DELETE': ['r:role:delete'],
  'R_ROLE_FIND': ['r:role:find'],
  'R_ROLE_UPDATE': ['r:role:update'],
  'R_ROOM_CREATE': ['r:room:create'],
  'R_ROOM_DELETE': ['r:room:delete'],
  'R_ROOM_FIND': ['r:room:find'],
  'R_ROOM_UPDATE': ['r:room:update'],
  'R_SETTING-GROUP_CREATE': ['r:setting-group:create'],
  'R_SETTING-GROUP_DELETE': ['r:setting-group:delete'],
  'R_SETTING-GROUP_FIND': ['r:setting-group:find'],
  'R_SETTING-GROUP_UPDATE': ['r:setting-group:update'],
  'R_SETTING-SITE_CREATE': ['r:setting-site:create'],
  'R_SETTING-SITE_DELETE': ['r:setting-site:delete'],
  'R_SETTING-SITE_FIND': ['r:setting-site:find'],
  'R_SETTING_CREATE': ['r:setting:create'],
  'R_SETTING_DELETE': ['r:setting:delete'],
  'R_SETTING_FIND': ['r:setting:find'],
  'R_SETTING_UPDATE': ['r:setting:update'],
  'R_SITE_CREATE': ['r:site:create'],
  'R_SITE_DELETE': ['r:site:delete'],
  'R_SITE_FIND': ['r:site:find'],
  'R_SITE_UPDATE': ['r:site:update'],
  'R_TEMPLATE_CREATE': ['r:template:create'],
  'R_TEMPLATE_FIND': ['r:template:find'],
  'R_TICKET_CANCEL': ['r:ticket:cancel'],
  'R_TICKET_CREATE': ['r:ticket:create'],
  'R_TICKET_FIND': ['r:ticket:find'],
  'R_TICKET_FIND_QR_CODE': ['r:ticket:findQRCode'],
  'R_TICKET_UPDATE': ['r:ticket:update'],
  'R_TICKET_VIEW_TICKET_DETAIL': ['r:ticket:viewTicketDetail'],
  'R_USER_CREATE': ['r:user:create'],
  'R_USER_EXPORT': ['r:user:export'],
  'R_USER_FIND': ['r:user:find'],
  'R_USER_IMPORT': ['r:user:import'],
  'R_USER_UPDATE': ['r:user:update']
}

export const REALM_ROLE_MAP = {
  'REALM_ADMIN': ['REALM_ADMIN']
}
